version: '3.8'

services:
  web:
    build: .
    container_name: php-apache-app
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    restart: unless-stopped

  mariadb:
    image: mariadb:10.5
    container_name: mariadb-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MARIADB_DATABASE: mydb
      MARIADB_USER: app_user
      MARIADB_PASSWORD: app_password
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8082:80"
    depends_on:
      - mariadb
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
    driver: local
