FROM alpine:latest

LABEL maintainer="Melih Cetinkaya"
LABEL description="Basic Docker container demonstration"
LABEL version="1.0"

CMD echo "Hello, Professor! This is a basic Docker container demonstration."